<?php
require_once __DIR__ . '/admin/config.php';
$content = get_site_content();
$success=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $name=sanitize_text($_POST['name']??''); $whatsapp=preg_replace('/\D+/','',$_POST['whatsapp']??''); $ptype=sanitize_text($_POST['property_type']??'');
  if($name===''||$whatsapp===''||$ptype===''){$error='Preencha todos os campos obrigatórios.';} else {
    $leads=load_json(LEADS_FILE,[]);
    $leads[]=['id'=>uniqid('lead_',true),'name'=>$name,'whatsapp'=>$whatsapp,'property_type'=>$ptype,'created_at'=>date('Y-m-d H:i:s')];
    if(save_json(LEADS_FILE,$leads)) $success='Lead enviado com sucesso! Em breve entraremos em contato.'; else $error='Não foi possível salvar seu lead.';
  }
}
?>
<!DOCTYPE html><html lang='pt-br'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><meta name='author' content='<?=e($content['seo']['author']??'')?>'><meta name='description' content='<?=e($content['seo']['description']??'')?>'><link href='assets/fonts/font-awesome-4.0.3/css/font-awesome.min.css' rel='stylesheet'><link rel='stylesheet' href='assets/bootstrap/css/bootstrap.css'><link rel='stylesheet' href='assets/css/style.css'><title><?=e($content['seo']['title']??'')?></title></head>
<body data-spy='scroll' data-target='.navigation' data-offset='90'><section id='home'></section><div class='wrapper'><div class='navigation fixed'><div class='container'><header class='navbar'><div class='navbar-header'><button class='navbar-toggle' type='button' data-toggle='collapse' data-target='.bs-navbar-collapse'><span class='icon-bar'></span><span class='icon-bar'></span><span class='icon-bar'></span></button><div class='navbar-brand nav' id='brand'><a href='index.php'><img src='assets/img/logo.png' alt='brand'></a></div></div><nav class='collapse navbar-collapse bs-navbar-collapse navbar-right'><ul class='nav navbar-nav'><?php foreach(($content['header']['menu']??[]) as $i=>$item):?><li class='<?=$i===0?'active':''?>'><a href='<?=e($item['url']??'#')?>'><?=e($item['label']??'')?></a></li><?php endforeach;?></ul></nav></header></div></div>
<section id='slider'><div class='flexslider loading'><div id='loading-icon'><i class='fa fa-cog fa-spin'></i></div><ul class='slides'><?php foreach(($content['hero']['slides']??[]) as $s): if(trim((string)$s)!==''):?><li class='slide'><img src='<?=e($s)?>' alt=''></li><?php endif; endforeach;?></ul></div><div class='slider-banner'><div class='container'><div class='row'><div class='col-md-8 col-sm-8'><div class='title'><h2><?=e($content['hero']['title']??'')?></h2><figure class='subtitle'><?=e($content['hero']['subtitle']??'')?></figure><i class='fa fa-arrow-circle-o-right'></i></div></div><div class='col-md-4 col-sm-4'><div class='form-slider-wrapper'><header><h3><?=e($content['hero']['form_title']??'')?></h3><h1><?=e($content['hero']['form_highlight']??'')?></h1></header><hr>
<?php if($success):?><div class='alert alert-success'><?=e($success)?></div><?php endif;?><?php if($error):?><div class='alert alert-danger'><?=e($error)?></div><?php endif;?>
<form method='post'><div class='form-group'><label>Nome<em>*</em></label><input type='text' class='form-control' name='name' required></div><div class='form-group'><label>WhatsApp<em>*</em></label><input type='text' class='form-control' name='whatsapp' required></div><div class='form-group'><label>Tipo de Imóvel<em>*</em></label><input type='text' class='form-control' name='property_type' required></div><div class='form-group'><button type='submit' class='btn btn-default'><?=e($content['hero']['button_text']??'Enviar')?></button></div></form><figure>*Campos obrigatórios</figure></div></div></div></div></div></section>
<section id='features' class='block'><div class='container'><header><h3><?=e($content['features']['title']??'')?></h3></header><div class='row'><div class='image-carousel'><div class='image-carousel-slide'><div class='row'><div class='col-md-5 col-sm-5 feature-media-col'><?php if(($content['features']['media_type']??'')==='video'):?><div class='feature-video-wrapper'><video controls preload='metadata' poster='<?=e($content['features']['video_poster']??'')?>'><source src='<?=e($content['features']['video_path']??'')?>' type='video/mp4'></video></div><?php else:?><img class='img-responsive' src='<?=e($content['features']['image_path']??'')?>' alt='Mídia principal'><?php endif;?></div><div class='col-md-7 col-sm-7 feature-content-col'><div class='row feature-steps'><?php foreach(($content['features']['cards']??[]) as $c):?><div class='col-md-4 col-sm-4'><div class='feature-box'><header><img src='<?=e($c['icon']??'')?>' alt=''><h4><?=e($c['title']??'')?></h4></header><p><?=e($c['description']??'')?></p></div></div><?php endforeach;?></div></div></div></div></div></div></div></section><hr><footer id='footer'><div class='container'><figure><?=e($content['footer']['copyright']??'')?></figure></div></footer></div>
<script src='assets/js/jquery-2.1.0.min.js'></script><script src='assets/js/jquery-migrate-1.2.1.min.js'></script><script src='assets/bootstrap/js/bootstrap.min.js'></script><script src='assets/js/owl.carousel.min.js'></script><script src='assets/js/jquery.flexslider-min.js'></script><script src='assets/js/jquery.validate.min.js'></script><script src='assets/js/retina-1.1.0.min.js'></script><script src='assets/js/jquery.magnific-popup.min.js'></script><script src='assets/js/jquery.fitvids.js'></script><script src='assets/js/scrollReveal.min.js'></script><script src='assets/js/custom.js'></script></body></html>
