<?php
require_once __DIR__ . '/admin/config.php';

$defaults = [
 'brand_name'=>'Quero Vender Meu Imóvel','hero_title'=>'Venda seu imóvel','hero_subtitle'=>'com segurança e pelo melhor valor de mercado',
 'hero_button_text'=>'QUERO SABER O VALOR DO MEU IMÓVEL','form_title'=>'Receba uma avaliação','form_highlight'=>'gratuita',
 'form_success_message'=>'Obrigado! Recebemos seus dados.','footer_copyright'=>'(C) QueroVenderMeuImóvel.com',
 'seo_title'=>'Quero Vender Meu Imóvel','seo_description'=>'Venda seu imóvel com segurança.','seo_author'=>'Quero Vender Meu Imóvel'
];
foreach($defaults as $k=>$v){$defaults[$k]=setting($k,$v);} 
$menu = json_decode(setting('menu_items','[{"text":"Início","link":"#home"},{"text":"Depoimentos","link":"#features"},{"text":"Como funciona","link":"#features"},{"text":"Contato","link":"#footer"}]'),true) ?: [];
$slides = json_decode(setting('hero_slides','["assets/img/slide001.png","assets/img/slide002.png","assets/img/slide003.png"]'),true) ?: [];
$cards = json_decode(setting('feature_cards','[]'),true) ?: [];
if (!$cards) $cards = [
 ['icon'=>'assets/img/icon-01.png','title'=>'1. Envie seus dados','description'=>'Informe os dados do imóvel e do proprietário para iniciarmos uma avaliação precisa.'],
 ['icon'=>'assets/img/icon-02.png','title'=>'2. Avaliamos seu imóvel','description'=>'Realizamos um estudo técnico de mercado para indicar o valor ideal de anúncio.'],
 ['icon'=>'assets/img/icon-03.png','title'=>'3. Definimos a estratégia','description'=>'Montamos um plano de divulgação com foco em velocidade de venda e melhor retorno.']
];
$feat=section('features');
$ok='';$err='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    $name=trim(strip_tags($_POST['name']??'')); $wa=trim(strip_tags($_POST['whatsapp']??'')); $pt=trim(strip_tags($_POST['property_type']??'')); $msg=trim(strip_tags($_POST['message']??''));
    if($name && $wa && $pt){
        $stmt=db()->prepare('INSERT INTO leads (name, whatsapp, property_type, message) VALUES (:n,:w,:p,:m)');
        $stmt->execute(['n'=>$name,'w'=>$wa,'p'=>$pt,'m'=>$msg]);
        $ok=$defaults['form_success_message'];
    } else { $err='Preencha os campos obrigatórios.'; }
}
?><!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="author" content="<?= e($defaults['seo_author']) ?>"><meta name="description" content="<?= e($defaults['seo_description']) ?>"><link href="assets/fonts/font-awesome-4.0.3/css/font-awesome.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/bootstrap/css/bootstrap.css"><link rel="stylesheet" href="assets/css/style.css"><title><?= e($defaults['seo_title']) ?></title></head><body data-spy="scroll" data-target=".navigation" data-offset="90"><section id="home"></section><div class="wrapper"><div class="navigation fixed"><div class="container"><header class="navbar"><div class="navbar-header"><button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><div class="navbar-brand nav" id="brand"><a href="index.php"><?= e($defaults['brand_name']) ?></a></div></div><nav class="collapse navbar-collapse bs-navbar-collapse navbar-right"><ul class="nav navbar-nav"><?php foreach($menu as $m): ?><li><a href="<?= e($m['link']??'#') ?>"><?= e($m['text']??'Link') ?></a></li><?php endforeach; ?></ul></nav></header></div></div>
<section id="slider"><div class="flexslider loading"><div id="loading-icon"><i class="fa fa-cog fa-spin"></i></div><ul class="slides"><?php foreach($slides as $s): ?><li class="slide"><img src="<?= e($s) ?>" alt=""></li><?php endforeach; ?></ul></div><div class="slider-banner"><div class="container"><div class="row"><div class="col-md-8"><div class="title"><h2><?= e($defaults['hero_title']) ?></h2><figure class="subtitle"><?= e($defaults['hero_subtitle']) ?></figure></div></div><div class="col-md-4"><div class="form-slider-wrapper"><header><h3><?= e($defaults['form_title']) ?></h3><h1><?= e($defaults['form_highlight']) ?></h1></header><hr><form method="post"><div class="form-group"><label>Nome*</label><input class="form-control" name="name" required></div><div class="form-group"><label>WhatsApp*</label><input class="form-control" name="whatsapp" required></div><div class="form-group"><label>Tipo de Imóvel*</label><input class="form-control" name="property_type" required></div><div class="form-group"><label>Mensagem</label><textarea class="form-control" name="message"></textarea></div><?php if($ok):?><div class="alert alert-success"><?= e($ok) ?></div><?php endif; ?><?php if($err):?><div class="alert alert-danger"><?= e($err) ?></div><?php endif; ?><button class="btn btn-default"><?= e($defaults['hero_button_text']) ?></button></form></div></div></div></div></div></section>
<section id="features" class="block"><div class="container"><header><h3><?= e($feat['title'] ?? 'Está difícil vender seu imóvel?') ?></h3></header><div class="row"><div class="col-md-5"><video controls preload="metadata" poster="<?= e(setting('feature_poster','assets/img/features-slide-01.jpg')) ?>"><source src="<?= e(setting('feature_video','assets/video/apresentacao.mp4')) ?>" type="video/mp4"></video></div><div class="col-md-7"><h4><?= e($feat['subtitle'] ?? 'Veja como é simples vender com estratégia profissional') ?></h4><p><?= e($feat['body'] ?? 'Nós cuidamos da avaliação, posicionamento e divulgação.') ?></p><div class="row"><?php foreach($cards as $c): ?><div class="col-md-4"><div class="feature-box"><header><img src="<?= e($c['icon'] ?? '') ?>" alt=""><h4><?= e($c['title'] ?? '') ?></h4></header><p><?= e($c['description'] ?? '') ?></p></div></div><?php endforeach; ?></div></div></div></div></section><hr><footer id="footer"><div class="container"><figure><?= e($defaults['footer_copyright']) ?></figure><p><?= e(setting('contact_whatsapp','')) ?> <?= e(setting('contact_email','')) ?></p></div></footer></div><script src="assets/js/jquery-2.1.0.min.js"></script><script src="assets/bootstrap/js/bootstrap.min.js"></script><script src="assets/js/jquery.flexslider-min.js"></script><script src="assets/js/custom.js"></script></body></html>
